### PR TITLE
12986 - Stack could be getting created not-on-a-map

### PR DESCRIPTION
**Pull request by Cattlesquat**
There is evidence elsewhere in StackMetrics.java (see line 271) that Stacks sometimes exist "not on a map". And if one is *created* not-on-a map, as tried to happen here, this line will blow up. So I put in null protection for the map.

### CODE REVIEW

**Comment by Cattlesquat** [comment]
Also, this is 2714, ho ho ho

**Comment by Cattlesquat** [comment]
And 3449 hahaha

**Comment by uckelman** [comment]
The fix for this one worries me, because it makes a case where no command gets created. @BrentEaston had a comment on one of the issues in which this occurs where he said that doing this would mask the actual bug.

**Comment by Cattlesquat** [comment]
Various ideas:
* We could just not create a stack in this case (where we aren't on a map). Just put the other piece in the same "location". 
* We could print some warning into the chat log (sort of like the "bad data" messages for expressions)

**Comment by Cattlesquat** [comment]
This bug is alive and well as recently as 3.3.2 (e.g. bug report 13337)

**Review by uckelman — APPROVED** [review]

**Pull request merged**
