### PR TITLE
10034 - MassPieceLoader - do not create empty layer levels 

### PR DESCRIPTION
**Pull request by claudiociardelli**

### CODE REVIEW

**Comment by claudiociardelli** [comment]
Probably for 3.6.0

**Comment by claudiociardelli** [comment]
Brent, ready for testing.

**Comment by claudiociardelli** [comment]
Labeled do not merge. Need to update documentation

**Comment by claudiociardelli** [comment]
Documentation up to data. Can be merged after review.
Found an unrelated bug. Copy Layer Trait does not work well with teh Emb extension of Embellishment. cf 11418

**Review by BrentEaston — COMMENTED** [review]
I can't seem to be able to reproduce the problem that this PR is fixing. Using 3.5.3, I am loading a folder with these images:
image
and creating a Layer with a single level of 'Ends with ' -back.
This creates 2 counters, one with a Layer and one without.  Is there a more complex case where this is failing?

**Pull request merged**
