### PR TITLE
10456 - Added Game Refresher documentation

### LINKED ISSUE #10456: Help button for Tools > Refresh Counters links to wrong place in Reference Manual
* The Help button links to somewhere which isn't to do with the Refresh Counters dialog.

* Is there any documentation for the Refresh Counters dialog at all?

### PR DESCRIPTION
**Pull request by Cattlesquat**
Fixes #10456 

Documented the two modes of the Game Refresher.

Did some basic write-ups. Feel free to add more. I don't know the ins and outs of the individual options so feel free to add detail. But I think I captured the main gist.

### CODE REVIEW

**Comment by BrentEaston** [comment]
Can add a quick overview of the Unused Image cleaner as well?

**Comment by Cattlesquat** [comment]
> Can add a quick overview of the Unused Image cleaner as well?

There's no help button on that dialog. If you know how to add one the then looks for the right kind of file then yeah I'd be happy to write it up.

**Comment by BrentEaston** [comment]
Oops, push it directly instead of via PR.

**Comment by Cattlesquat** [comment]
Wrote up RemoveUnusedImages. Also got involved in improving some of the crosslinks between pages and stuff (better navigability in certain key sections of the reference manual)

**Review by BrentEaston — APPROVED** [review]

**Pull request merged**
