### PR TITLE
Log connection failures

### PR DESCRIPTION
**Pull request by uckelman**

### CODE REVIEW

**Comment by BrentEaston** [comment]
@uckelman Do you want to bring this into 3.5.6, or just leave for 3.6?

**Comment by uckelman** [comment]
I was hoping that somebody having the problem this targets would try the build first. I'll give them another poke.

**Comment by BrentEaston** [comment]
I guess I should try it. Bug reports have never worked for me :)

**Comment by BrentEaston** [comment]
I hard-coded a NPE into a trait to trigger a bug.

Log file pre submitting the bug:
[pre-send-bug.log](https://github.com/vassalengine/vassal/files/6303519/pre-send-bug.log)

Log file post submitting the bug:
[post-send-bug.log](https://github.com/vassalengine/vassal/files/6303523/post-send-bug.log)

BugUtils:32 final String result = IOUtils.toString(in, StandardCharsets.UTF_8);

is returning a null String, not "0" as expected

**Pull request merged**
