### PR TITLE
11462 - Don't +1 inventory sum if property isn't even defined

### LINKED ISSUE #11462: Inventory sum_propName adds 1 for unit that does not have propName defined instead of 0

### PR DESCRIPTION
**Pull request by Cattlesquat**
Fixes #11462

### CODE REVIEW

**Comment by BrentEaston** [comment]
I remember seeing a similar bug report for the Sum() beanshell function. Not sure if that was ever fixed?

**Comment by Cattlesquat** [comment]
@BrentEaston I took a scan through ExpressionInterpreter and I couldn't find anything that looked like it would have that problem, so maybe if it existed we already fixed it?

**Comment by BrentEaston** [comment]
@Cattlesquat , Ah, I was thinking of this same issue!

**Comment by BrentEaston** [comment]
What's the 'ter' file in the commit?

**Pull request merged**
