### PR TITLE
11506 - Predefined Setup "menus" with blank names will not be shown

### LINKED ISSUE #11506: Hide blank named menu & its contents from the Pre-Defined Setups list
This idea is that empty (or special coded) menu names could be interpreted by Vassal as “do not display this branch to the user”. The benefit example is Commands & Colors: Ancients which includes custom code to navigate its several hundred PDS files, most of which do not need to appear in the standard Files... PDS menus. With this change, such files could be minimally defined in a hidden Pre-Defined Setups branch, so that they still get picked up by the Pre-Defined Setups Refresh tool.

Request details in [this](https://forum.vassalengine.org/t/hide-blank-named-menu-its-contents-from-the-pre-defined-setups-list/74810/2) forum post.

### PR DESCRIPTION
**Pull request by Cattlesquat**
Special gift for Command & Colors :)

Fixes #11506

### CODE REVIEW

**Comment by Cattlesquat** [comment]
@riverwanderer Give a test and see if this does what you need it to do

**Comment by Cattlesquat** [comment]
Fixes #11506

**Comment by riverwanderer** [comment]
Tested VASSAL-3.7.0-SNAPSHOT-e97f88f-11506 by editting the Pre Set Scenario menu item - to blank the menu. Saved module and re-opened, but the (now blank) scenario menu was still there.

Did I test the right snapshot ?

**Comment by Cattlesquat** [comment]
So in theory it has to be one of the ones with the "Parent Menu" checkbox checked that you blank the name of. Is that what you did? When I tested it seemed to work

**Comment by riverwanderer** [comment]
I didn't do that, so I repeated the testing; this time creating a blank "parent menu". Moving in a pre-existing folder hierarchy, the blank still appears. I also got erorrs when I moved in the files to a blank named parent:

```
2023-02-28 00:05:18,996 [72086-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "text" is null
	at VASSAL.tools.menu.MenuProxy.lambda$setText$1(MenuProxy.java:75)
	at VASSAL.tools.menu.AbstractProxy.forEachPeer(AbstractProxy.java:37)
	at VASSAL.tools.menu.MenuProxy.setText(MenuProxy.java:75)
	at VASSAL.build.module.PredefinedSetup.setAttribute(PredefinedSetup.java:163)
	at VASSAL.configure.AutoConfigurer.propertyChange(AutoConfigurer.java:243)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at VASSAL.configure.Configurer.setValue(Configurer.java:118)
	at VASSAL.configure.StringConfigurer.setValue(StringConfigurer.java:90)
	at VASSAL.configure.AutoConfigurer.reset(AutoConfigurer.java:220)
	at VASSAL.build.AbstractConfigurable.getConfigurer(AbstractConfigurable.java:215)
	at VASSAL.configure.ConfigureTree.updateEditMenu(ConfigureTree.java:1546)
	at VASSAL.configure.ConfigureTree.valueChanged(ConfigureTree.java:1531)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:3018)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3519)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:650)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1120)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:306)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:200)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1708)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2761)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4096)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressedDND(BasicTreeUI.java:4073)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:4032)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Cattlesquat** [comment]
@riverwanderer Okay I have fixed that crash (oops). 

Meanwhile... the menu hiding is working fine for me on Windows. *Possibly* Java Swing on Mac doesn't support hiding submenus? I've added a thing to try hiding individual PredefinedSetup entries as well if their names are blank (I think that's probably what you were trying to do the first time) -- so anyway please try blanking some individual ones and see if they at least disappear? (in the new version building now)

**Comment by riverwanderer** [comment]
VASSAL-3.7.0-SNAPSHOT-8eca12a-master-macos-x86_64 - works with no crashing but does not fix the issue (I suspect this build doesn't include the fix).

The build VASSAL-3.7.0-SNAPSHOT-21cff48-11506-macos-x86_64 causes a similar Vassal startup crash to that I reported just now for a different issue / build:

```
2023-03-01 10:10:25,257 [32788-main] INFO  VASSAL.launch.StartUp - Starting
2023-03-01 10:10:25,269 [32788-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 13.2.1 x86_64
2023-03-01 10:10:25,269 [32788-main] INFO  VASSAL.launch.StartUp - Java version 19.0.2
2023-03-01 10:10:25,269 [32788-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL 2.app/Contents/MacOS/jre
2023-03-01 10:10:25,269 [32788-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.0-SNAPSHOT-21cff48-11506
2023-03-01 10:10:25,833 [32788-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManager - Manager
2023-03-01 10:10:26,486 [32788-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.ExceptionInInitializerError: null
	at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Cannot read field "width" because "this.bounds" is null
	at VASSAL.preferences.PositionOption.setFrameBounds(PositionOption.java:164)
	at VASSAL.preferences.PositionOption.<init>(PositionOption.java:49)
	at VASSAL.preferences.PositionOption.<init>(PositionOption.java:66)
	at VASSAL.launch.ModuleManagerWindow.<init>(ModuleManagerWindow.java:440)
	at VASSAL.launch.ModuleManagerWindow.<clinit>(ModuleManagerWindow.java:187)
	... 14 common frames omitted

```

**Comment by Cattlesquat** [comment]
@riverwanderer This one I've also just rebased to get around the problem that crept in from another branch's bug -- when new build is up, give it another try.

**Comment by riverwanderer** [comment]
Installed this but it now crashes silently - just like you get if you try installing and running the build for the wrong Mac architecture, except it wasn't the wrong one:
image

**Comment by riverwanderer** [comment]
Fixed the "crash" - my fault, another Vassal test app was already running on my machine. Now I can run the build, it doesn't crash when I add in a blank pre-set but e.g., this at the top-level... 
image

Still shows in the menu (even shows if completely empty):
image

**Comment by riverwanderer** [comment]
When I try these things, the best I can get is for the menu item to temporarily disappear when the change is applied, only to re-appear after another edit, or at least when the module is re-opened.

**Comment by Cattlesquat** [comment]
@riverwanderer Ah, that's a good clue -- try the "new new" version when its ready

**Comment by riverwanderer** [comment]
Success! Tested VASSAL-3.7.0-SNAPSHOT-321302d-11506-macos -  The module with changed menus that I prepared earlier now hides the blank menus and its contents.  Moving the structure into another PDS parent doesn't affect it - the blank child stays hidden.

Side note - as expected, Refresh and the Scenario Chooser (custom code) contain to operate fine, regardless of the scenario file being under a blank parent.

**Pull request merged**
