### PR TITLE
introducing_constant_for_property_name_baby_step

### PR DESCRIPTION
**Pull request by ffatheranderson**
Baby step commit.

### CODE REVIEW

**Comment by uckelman** [comment]
Fix the conflicts and I'll merge it.

**Comment by BrentEaston** [comment]
I'm wondering whether these changes should be merged in with the change to include Custom VM Options in a config file?

**Comment by uckelman** [comment]
The port for talking with the MM is set by the MM. The MM picks a port that's not in use. If we made that user-configurable, the user could pick a bad port, which isn't possible now. I don't see a use-case for making this user-configurable.

(And I'm still waiting for the conflicts to be resolved...)

**Comment by ffatheranderson** [comment]
> The port for talking with the MM is set by the MM. The MM picks a port that's not in use. If we made that user-configurable, the user could pick a bad port, which isn't possible now. I don't see a use-case for making this user-configurable.
> 
> (And I'm still waiting for the conflicts to be resolved...)

**Comment by ffatheranderson** [comment]
I do not feel motivated currently to proceed working on this. Sorry about this. I closed PR for now.

**Comment by uckelman** [comment]
Alright. The comment regarding making the MM port user-configurable was in relation to #149, not this PR.

**Pull request closed without merging**
