### PR TITLE
14070 - Array Configurers move cursor to newly created entry

### PR DESCRIPTION
**Pull request by BrentEaston**

### CODE REVIEW

**Comment by uckelman** [comment]
Where's a good place to look to test this?

**Comment by BrentEaston** [comment]
Define Sides String Lists
Trigger Action for Hotkey Lists.
Dynamic Property for KeyCommandLists

**Comment by uckelman** [comment]
Maybe I don't understand what this is supposed to do, in that case. I went to the Player Sides in the PoG module and added a new side. The insertion point didn't appear in the new row.

**Comment by BrentEaston** [comment]
Hmm. Yes, that is a good test and it certainly does put the insertion point in a new row on Windows. I will check linux.

**Comment by BrentEaston** [comment]
Works perfectly for me on Ubuntu as well ???

**Comment by uckelman** [comment]
Uh, I have no idea what was wrong before. This behaved as advertised when I checked it just now.

**Pull request merged**
