### PR TITLE
Text label doc update

### PR DESCRIPTION
**Pull request by claudiociardelli**

### CODE REVIEW

**Comment by BrentEaston** [comment]
@Cattlesquat could you review this PR please. One of your Chatter mods seems to have been sucked in. Ta.

**Comment by Cattlesquat** [comment]
It's weird that that's there, but fortunately it contains the "correct code" for that piece of Chatter.

**Review by BrentEaston — CHANGES_REQUESTED** [review]
Hi Claudio, could you please rebase this PR on the current Master? It has sucked in a change from an old version of Chatter. Brian tells me the command you need to do is:

(1) get his master branch completely up to date:
git checkout master
git fetch upstream
git merge upstream/master
git push origin refs/heads/master:master
(2) Check out whatever branch he has that in
git checkout TextLabelDocUpdate
(3) rebase on master
git rebase master
HOPEFULLY that just magically all happens with no "merge conflicts", in which case he can then:
git push -f
And all will be well. But if there are merge conflicts, then for EACH merge conflict that comes up, first thing is:
git mergetool
Do what it says, then...
git add *Chatter.java
 or whatever file had merge conflict
git rebase --continue
And keep doing that until it says it succeeded and THEN do the 
git push-f

But since you only changed the one AsciiDoc file, the rebase should work.

Thanks.

**Comment by claudiociardelli** [comment]
Did the cli rebasing steps suggested. All went well. Here is the last log

D:\git_vassal>git push -f
Enumerating objects: 31, done.
Counting objects: 100% (31/31), done.
Delta compression using up to 8 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (24/24), 2.22 KiB | 90.00 KiB/s, done.
Total 24 (delta 15), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (15/15), completed with 5 local objects.
To https://github.com/claudiociardelli/vassal.git
 + 32573bb86...4c9b28cbd TextLabelDocUpdate -> TextLabelDocUpdate (forced update)

Let me know if ok now

**Pull request merged**
