### PR TITLE
10474 - Movement traits need to update cargo's mat after movement before applying apply-on-move keystroke

### PR DESCRIPTION
**Pull request by Cattlesquat**
Send-to-Location, Rotate, and Move-Fixed-Distance all had the "update our mat based on where we moved to" logic _after_ the apply-on-move key was applied to them. That was incorrect and was leading to "Current Mat" property not being updated correctly, wrong messages being printed, etc. 

I've moved the code blocks to the right location and verified that this was removing the "wrong messages" in my module. 

PieceMover was already working correctly (which is why I didn't notice this earlier)

### CODE REVIEW

**Comment by uckelman** [comment]
It's kind of gross that the same block of code is copied there four times.

**Comment by Cattlesquat** [comment]
> It's kind of gross that the same block of code is copied there four times.

Got a preference where to centralize it?

**Comment by Cattlesquat** [comment]
Cool - all taken care of. Code looks nice now. I'm always afraid to introduce "static" w/o being told to :)

**Review by uckelman — APPROVED** [review]

**Comment by uckelman** [comment]
Something got confused here. It's merged.

**Pull request closed without merging**
