### PR TITLE
10272 Don't auto-name new regions a long string

### PR DESCRIPTION
**Pull request by Cattlesquat**
Right new every time you make a new region it gets auto-named "New Region" which means you have to first delete all of that text every single time. So I've changed it to a blank string which seems a lot easier-to-use.

### CODE REVIEW

**Comment by Cattlesquat** [comment]
Issue #10272

**Review by BrentEaston — CHANGES_REQUESTED** [review]
I think this would be better if you change the code to explicitly set the name to the null string than setting it to a translation string that has been set to null. This is just confusing and someone in the future is going to put that back thinking it is a missing translation, or a translator may feel the need to translate 'New Region'.

**Comment by Cattlesquat** [comment]
Oh okay I had *thought* about doing that but then worried that would make it harder to change later. But that might be a silly worry since I obviously think the _proper_ result is to have these be blank.

**Comment by Cattlesquat** [comment]
Should be all set now.

**Review by BrentEaston — APPROVED** [review]

**Pull request merged**
