### PR TITLE
added saving/reading of transparency for color backgrounds

### PR DESCRIPTION
**Pull request by jasonestewart**
Fix for bug 13307: http://www.vassalengine.org/tracker/show_bug.cgi?id=13307

### CODE REVIEW

**Comment by Cattlesquat** [comment]
Nice!

**Comment by jasonestewart** [comment]
finally got around to teaching myself enough JUnit to write a test...

**Comment by Cattlesquat** [comment]
Holy crap, @uckelman I think you're going to like this guy :D :D :D

**Comment by Cattlesquat** [comment]
Btw jason there is a discord "chat room" here where various code-oriented VASSAL folks hang out: https://discord.gg/P8tcJv

**Review by uckelman — APPROVED** [review]

**Comment by uckelman** [comment]
Looks good. Thanks for the contribution.

**Pull request merged**
