### PR TITLE
14422 - Refresh Counters - Fixed Match Layers by Name

### PR DESCRIPTION
**Pull request by claudiociardelli**

### CODE REVIEW

**Comment by claudiociardelli** [comment]
Oops, fixed the wrong bug. THis PR fixes 14422, not 14440.

**Comment by claudiociardelli** [comment]
Mark tested the fix and confirms Refresh with Match layer by name now works.

**Comment by uckelman** [comment]
Do you want this against `release-3.5.6` instead?

**Comment by claudiociardelli** [comment]
Yes please. 3.5.6

**Comment by uckelman** [comment]
You'll need to rebase this PR, in that case.

**Comment by uckelman** [comment]
This has been merged to `release-3.5.6` as #924.

**Pull request closed without merging**
