### PR TITLE
11121 - Fix problem where undo wasn't allowed when starting a new game with logging turned on

### PR DESCRIPTION
**Pull request by Cattlesquat**

### CODE REVIEW

**Comment by riverwanderer** [comment]
I’ve seen this bug but wasn’t able to replicate. I guess because I failed to replicate the “with log file open” but.

**Comment by Cattlesquat** [comment]
> I’ve seen this bug but wasn’t able to replicate. I guess because I failed to replicate the “with log file open” but.

Yes that was precisely my repro problem too -- I'd heard various reports of undo being incorrectly not available, but whenever I'd "check" it seemed like it worked -- until I finally hit the correct repro case.

**Comment by uckelman** [comment]
That's hilarious. That's all it took to fix?

**Comment by Cattlesquat** [comment]
Lol yes, it was just a missed code path

**Pull request merged**
