### PR TITLE
13196 Ctrl+Click toggles rather than "only" deselects

### PR DESCRIPTION
**Pull request by Cattlesquat**
The funny little side-bit is the amount of time I used to spend worrying about how this behavior in PoG must be something I'd fucked up with a custom class.

### CODE REVIEW

**Comment by uckelman** [comment]
Problem: I can't toggle individual units in an expanded stack this way.

**Comment by Cattlesquat** [comment]
Hunh, I'll go take a look

**Comment by Cattlesquat** [comment]
An, that would be because this didn't actually _have_ the last else. Even though, as we know, Control "only" deselects ;-) 
`
          Stack s = p.getParent();
          if (s == null) {
            kbuf.remove(p);
          }
          else if (!s.isExpanded()) {
            s.asList().forEach(gamePiece -> KeyBuffer.getBuffer().remove(gamePiece));
          } 
          else {
            kbuf.remove(p);  
          }
`

**Comment by Cattlesquat** [comment]
Oh great, earlier today github wouldn't put any indentation in a code paste. Now it won't even put line breaks, lol.

**Comment by Cattlesquat** [comment]
Anyway, all fixed.

**Comment by Cattlesquat** [comment]
@yanlyub Help! This won't resolve with the "resolve conflicts" button. I tried a "rebase on master" and it turned into an unending clusterfuck of mysterious problems. Like a LOT more conflicts than "just in this one file". I eventually did "git rebase --abort".

**Comment by Cattlesquat** [comment]
(And I should mention NONE of the PR's will resolve with the regular button)

**Comment by Cattlesquat** [comment]
Hunh. I wonder what I typed wrong the first time. This time everything went okay! Glad I was able to delete that mess and try again :-)

**Pull request merged**
