### PR TITLE
12645 Respect localisation when filtering sides

### PR DESCRIPTION
**Pull request by riverwanderer**
Possible fix for #12645 - suspect that Side is not localized before testing for removal from Available sides.

### CODE REVIEW

**Comment by riverwanderer** [comment]
Still works in standard mode but doesn't seem to fix localization issue.

**Comment by riverwanderer** [comment]
Fix is predicated on understanding that PlayerRoster.java _availableSides_  is a list of translated sides and that therefore adds to _alreadyTaken_ should also be translated. Therefore 3 instances of `alreadyTaken.add(p.Side)` are replaced with `alreadyTaken.add alreadyTaken.add(p.getLocalizedSide())`.

**Comment by uckelman** [comment]
Is this ready to review?

**Comment by riverwanderer** [comment]
> Is this ready to review?

yes

**Comment by Cattlesquat** [comment]
Looks okay to me

**Pull request merged**
