### PR TITLE
Toggle password visibility

### PR DESCRIPTION
**Pull request by yanlyub**

### CODE REVIEW

**Comment by uckelman** [comment]
The height of the whole row is bad: 

image

**Comment by uckelman** [comment]
The best way is to use a MigLayout for these.

**Comment by yanlyub** [comment]
> The height of the whole row is bad:
> image

I can't reproduce that, I increased the row height to 40 now, hope it's enough.

**Comment by uckelman** [comment]
Setting fixed sizes for those components isn't the best. The last commit here (https://github.com/uckelman/vassal/commits/pw_layout) uses different layout.

**Comment by uckelman** [comment]
Closing in favor of PR 343, which also contains the commit from this PR.

**Pull request closed without merging**
