### PR TITLE
Vassal-doc Maven module

### PR DESCRIPTION
**Pull request by yanlyub**
This moves the `/doc` directory into a new Maven module `vassal-doc`.

### CODE REVIEW

**Comment by yanlyub** [comment]
I moved the `doc/` folder with the IDE the first time around and it changed a lot of the html files, probably their line endings. Now I moved them with `git mv` on the command line, this didn't change them.

**Comment by uckelman** [comment]
I'm worried that merging this will cause many conflicts for #117 and vice versa. Please advise.

**Comment by yanlyub** [comment]
Yes it will, let's wait with this one until #117 is merged then I will resolve conflicts. I would put this back into "draft mode" but can't find a way to do it.

**Comment by uckelman** [comment]
The link for draft mode is something I have to hunt for every time... Upper right, next to "Still in progress?" there's a "Convert to draft" link.

**Comment by yanlyub** [comment]
Thanks, this is better.

**Comment by yanlyub** [comment]
Ready to be merged.

**Pull request merged**
