### PR TITLE
Bug 13197: Mac interface cleanup and Legacy preference

### PR DESCRIPTION
**Pull request by uckelman**
@Cattlesquat I pulled your Bugfix13197 branch, did `git rebase master` on it, resolved the one conflict in KeyBufferer, and pushed it back. This is it.

### CODE REVIEW

**Comment by Cattlesquat** [comment]
Well okay then! Probably ready to merge... looks like exactly the right commits and none of the "earlier bullshit".

**Comment by Cattlesquat** [comment]
Also I've made it to chapter 2 of "the book", haha :D

**Comment by Cattlesquat** [comment]
Hey actually -- check out #110 and see if I did it right. Practice and stuff.

**Comment by uckelman** [comment]
Closing in favor of #110.

**Pull request closed without merging**
